### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by nh-99** [sevein/archivematica#15]
There seems to be an issue with the dashboard service, I'm getting a 500 error and this is in the logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 239, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/usr/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 366, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/src/archivematica/src/dashboard/src/urls.py", line 26, in <module>
    url(r'^fpr/', include('fpr.urls')),
  File "/usr/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 28, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/src/archivematica/src/dashboard/src/fpr/urls.py", line 2, in <module>
    from fpr import views
  File "/src/archivematica/src/dashboard/src/fpr/views.py", line 20, in <module>
    from fpr import forms as fprforms
  File "/src/archivematica/src/dashboard/src/fpr/forms.py", line 13, in <module>
    class FormatForm(forms.ModelForm):
  File "/src/archivematica/src/dashboard/src/fpr/forms.py", line 14, in FormatForm
    group = forms.ChoiceField(choices=fprmodels.FormatGroup.objects.all())
  File "/usr/local/lib/python2.7/site-packages/django/forms/fields.py", line 778, in __init__
    self.choices = choices
  File "/usr/local/lib/python2.7/site-packages/django/forms/fields.py", line 792, in _set_choices
    self._choices = self.widget.choices = list(value)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 141, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
ProgrammingError: (1146, "Table 'MCP.fpr_formatgroup' doesn't exist")
```

**Comment by sevein** [comment]
Hi @nh-99! Not sure if that's the dashboard missing the `archivematica-fpr-admin` submodule (https://github.com/artefactual/archivematica/blob/qa/1.x/.gitmodules) or a problem with database migrations. Can you tell me more about how are you running your environment? Did you use the prod or the dev env?

**Comment by sevein** [comment]
Actually based on your trace it seems that the fpr code is there...

**Comment by nh-99** [comment]
I used the production environment, just ran the shell script. This was what happened after it ran, I didn't modify anything.

Another thing to note is that I was running Archivematica on the host OS beforehand, but I stopped all of the services it was running so those ports are going to the docker containers. Let me know if you need anything else!

**Comment by sevein** [comment]
Cool, thanks for trying. I'll see what I can do! Are you in a rush?

**Comment by nh-99** [comment]
Eh, not really :) whenever you get a chance to check it out that would be awesome. I'll trying playing with stuff in the meantime

**Comment by nh-99** [comment]
Oh cool, so I tracked it down! Connected into a shell in the docker container and ran migrations on the app, now it seems to be working fine! Not sure why they didn't get run in the first place though...

**Comment by nh-99** [comment]
I think that the issue had to do with the old archivematica install I had on the host OS. After cleaning that up and remaking all the docker containers, it works perfectly! Excellent piece of software, I look forward to easily deploying archivematica from now on! Thank you!

**Comment by sevein** [comment]
Oh interesting. `syncdb` is definitely invoked, but maybe something is missing?

I'm going to reopen if you don't mind so I won't forget to revisit.

**Comment by nh-99** [comment]
Yeah sure thing. I think that the issue was just happening because I already had archivematica installed on the server and it was claiming the active ports (including mysql). Then the containers couldn't bind those ports, so they weren't able to connect to each other to do things such as sync the database. It all seems to be working perfectly now though!
